export const ClienteleTableData = [
  {
    id: "1",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "2",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "3",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "4",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "5",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "6",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "7",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "8",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "9",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "10",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "11",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "12",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "13",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "14",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "15",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "16",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "17",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "18",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "19",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "20",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "21",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "22",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "23",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "24",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "25",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "26",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "27",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "28",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "29",
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: "30",
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
];

export const BusinessDetailsData = [
  {
    businessname: "PursBusiness Limited",
    type: "NGO",
    industry: "Fintech",
    fullname: "Temitope Williams",
    gender: "Male",
    phonenumber: "0806xxxxx250",
    emailaddress: "yourmail@gmail.com",
    houseNumber: "No 23",
    streetName: "Obawole street  nidike",
    state: "Ogun",
    idNumber: "23456789344",
    bvn: "3444678099735",
  },
];
