export const ClienteleTableData = [
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
];
